[参考：https://pytorch.org/docs/stable/torch.html](https://pytorch.org/docs/stable/torch.htmll)

In [1]:
import torch

In [4]:
x = torch.tensor([[1,2,3]])   # torch.tensor会复制一份数据
for i in x:
    print(i) # tensor可以使用迭代器

tensor([1, 2, 3])


In [26]:
x = torch.ones([3,2,2],dtype=torch.float64) #shape
x

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], dtype=torch.float64)

In [15]:
x = torch.zeros_like(x)
x

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [16]:
x = torch.ones_like(x)
x

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [27]:
import numpy as np
y = np.array([1,2,3])
x = torch.from_numpy(y)
x

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
z = x.numpy()
z

array([1, 2, 3])

In [36]:
x = torch.arange(1,10,2)  #结果为（end-start）/step向上取整
x

tensor([1, 3, 5, 7, 9])

In [38]:
x = torch.linspace(3, 10, steps=5)   #在3-10之间取5个数
x

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [39]:
torch.eye(3)  #生成单位矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
torch.full((2, 3), 3.141592)  #使用值填充

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [41]:
 torch.randn(2, 3)

tensor([[ 1.2643,  0.7357, -0.4602],
        [-1.1076,  1.5763,  0.7526]])